[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on Conventional Commits."""

body = """
{%- if version %}
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}
## [Unreleased] - {{ now() | date(format="%Y-%m-%d") }}
{% endif %}

{%- for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {% if commit.scope %}{{ commit.scope }}: {% endif %}{{ commit.raw_message | split(pat="\n") | first }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/commit/{{ commit.id }}))
{%- if commit.body %}
{%- for line in commit.body | split(pat="\n") %}
{%- if line | trim != "" %}
  {{ line | trim }}
{%- endif %}
{%- endfor %}
{%- endif %}
{% endfor %}
{%- endfor -%}
"""

trim = false
render_always = false

postprocessors = [
    { pattern = '\(#([0-9]+)\)', replace = "[#${1}]({{ repository_url }}/issues/${1})" }
]

[remote.github]
owner = "williamcanin"
repo = "tildr"
token = "$GITHUB_TOKEN"
#token = "" # Leaving it blank disables API calls, and Cliff will not fetch PRs.

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
top_order = true
use_branch_tags = false

# Repo URL (used in links)
repository_url = "https://github.com/orbitbits/tildr"

commit_preprocessors = [
    # Normalizes BREAKING CHANGE in the body
    { pattern = "BREAKING CHANGE:", replace = "BREAKING:" },
    # Escape HTML tag
    { pattern = "<([^>]+)>", replace = "`<$1>`" }
]

commit_parsers = [
    { message = "^feat(\\([^)]+\\))?!?:", group = "Features", breaking = true },
    { message = "^feat(\\([^)]+\\))?:", group = "Features" },
    { message = "^fix(\\([^)]+\\))?!?:", group = "Bug Fixes", breaking = true },
    { message = "^fix(\\([^)]+\\))?:", group = "Bug Fixes" },
    { message = "^perf(\\([^)]+\\))?!?:", group = "Performance", breaking = true },
    { message = "^perf(\\([^)]+\\))?:", group = "Performance" },
    { message = "^refactor(\\([^)]+\\))?!?:", group = "Refactoring", breaking = true },
    { message = "^refactor(\\([^)]+\\))?:", group = "Refactoring" },
    # Ignore
    { message = "^docs(\\([^)]+\\))?:", skip = true },
    { message = "^test(\\([^)]+\\))?:", skip = true },
    { message = "^build(\\([^)]+\\))?:", skip = true },
    { message = "^ci(\\([^)]+\\))?:", skip = true },
    { message = "^chore(\\([^)]+\\))?:", skip = true },
    { message = "^style(\\([^)]+\\))?:", skip = true },
    { message = "^add(\\([^)]+\\))?:", skip = true },
]

# Optional: Ignore specific commits
commit_ignore = [
    "^Merge branch",
    "^Merge pull request",
    "^Initial commit$"
]

# tag control
tag_pattern = "v[0-9]*"
skip_tags = ""
ignore_tags = ""

# ordering
sort_commits = "newest"
