use anyhow::{Context as _, Result};
use console::style;
use std::fs;
use std::io::Write;
use std::path::Path;
use std::process::Command as StdCommand;
use tildr_core::context::Context;

pub fn run(ctx: &Context, output: &Option<String>) -> Result<()> {
  let git_available = ctx.config.git.operations_enabled();
  let has_secrets = ctx.repo_path.join(".tildr/encrypted.gpg").exists();
  let remote_url = if git_available {
    get_remote_url(&ctx.repo_path)
  } else {
    None
  };

  let script = generate_script(
    &ctx.repo_path,
    remote_url.as_deref(),
    has_secrets,
    git_available,
  );

  match output {
    Some(path) => {
      let path = Path::new(path);
      if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
          .with_context(|| format!("Failed to create directory: {}", parent.display()))?;
      }
      let mut file = fs::File::create(path)
        .with_context(|| format!("Failed to create file: {}", path.display()))?;
      file.write_all(script.as_bytes())?;
      println!(
        "{} {}",
        style("Snapshot script created:").green().bold(),
        path.display()
      );
    }
    None => {
      print!("{}", script);
    }
  }

  Ok(())
}

fn get_remote_url(repo_path: &Path) -> Option<String> {
  let output = StdCommand::new("git")
    .args(["remote", "get-url", "origin"])
    .current_dir(repo_path)
    .output()
    .ok()?;

  if !output.status.success() {
    return None;
  }

  let url = String::from_utf8_lossy(&output.stdout).trim().to_string();
  if url.is_empty() { None } else { Some(url) }
}

fn generate_script(
  repo_path: &Path,
  remote_url: Option<&str>,
  has_secrets: bool,
  git_available: bool,
) -> String {
  let today = chrono::Local::now().format("%Y-%m-%d");
  let repo_display = repo_path.display();
  let repo_name = repo_path
    .file_name()
    .map(|n| n.to_string_lossy().to_string())
    .unwrap_or_else(|| ".dotfiles".to_string());

  let mut script = format!(
    r#"#!/usr/bin/env bash
# Generated by `tildr snapshot` on {today}
# Repository: {repo_display}
set -euo pipefail

info()  {{ echo -e "\033[32m[INFO]\033[0m  $*"; }}
warn()  {{ echo -e "\033[33m[WARN]\033[0m  $*"; }}
error() {{ echo -e "\033[31m[ERROR]\033[0m $*"; exit 1; }}

echo "=== Tildr Bootstrap Script ==="
echo ""
"#,
    today = today,
    repo_display = repo_display,
  );

  script.push_str(
    r#"info "[1/5] Checking prerequisites..."

command -v git >/dev/null 2>&1 || error "git is not installed. Please install git first."
command -v tildr >/dev/null 2>&1 || error "tildr is not installed. Please install tildr first."
"#,
  );

  if has_secrets {
    script.push_str(
      r#"command -v gpg >/dev/null 2>&1 || error "gpg is not installed. It is required for secret management."
"#,
    );
  }

  if git_available {
    if let Some(url) = remote_url {
      script.push_str(&format!(
        r#"
info "[2/5] Cloning repository..."
REPO_URL="{url}"
DEST="$HOME/{repo_name}"

if [ -d "$DEST" ]; then
  info "Repository already exists at $DEST, skipping clone"
else
  git clone "$REPO_URL" "$DEST"
fi
"#,
        url = url,
        repo_name = repo_name,
      ));
    } else {
      script.push_str(&format!(
        r#"
info "[2/5] Setting up repository..."
DEST="$HOME/{repo_name}"

if [ -d "$DEST" ]; then
  info "Repository already exists at $DEST, skipping creation"
else
  mkdir -p "$DEST"
  git -C "$DEST" init
  warn "No remote configured. Run 'git remote add origin <url>' inside $DEST"
fi
"#,
        repo_name = repo_name,
      ));
    }
  } else {
    script.push_str(&format!(
      r#"
info "[2/5] Setting up repository..."
DEST="$HOME/{repo_name}"

if [ -d "$DEST" ]; then
  info "Repository already exists at $DEST, skipping creation"
else
  mkdir -p "$DEST"
  warn "Git is not available. Repository will not be version-controlled."
fi
"#,
      repo_name = repo_name,
    ));
  }

  script.push_str(
    r#"
info "[3/5] Initializing Tildr..."
if [ ! -f "$HOME/.config/tildr/config.toml" ]; then
  tildr init --repo "$DEST" --no-git 2>/dev/null || tildr init --repo "$DEST"
else
  info "Config already exists, skipping init"
fi

info "[4/5] Applying symlinks..."
tildr apply
"#,
  );

  if has_secrets {
    script.push_str(
      r#"
info "[5/5] Decrypting secrets..."
if [ -f "$DEST/.tildr/encrypted.gpg" ]; then
  tildr secret decrypt
else
  info "No secrets to decrypt"
fi
"#,
    );
  } else {
    script.push_str(
      r#"
info "[5/5] No secrets to decrypt, skipping."
"#,
    );
  }

  script.push_str(
    r#"
echo ""
info "=== Bootstrap complete ==="
info "Run 'tildr status' to verify your setup."
info "Run 'tildr doctor' to check for any issues."
"#,
  );

  script
}
