#!/usr/bin/env sh
# To use, run the following command only once in the project directory:
#   git config core.hooksPath hooks

echo "[tildr] Running checks..."

# ----- Checks -----
if ! make check; then
  echo "[tildr] Checks failed. Commit aborted."
  exit 1
fi

echo "[tildr] OK"
exit 0
